remote_theme: pmarsceill/just-the-docs
color_scheme: dark_orange
title: IoT-Utilities
logo: "https://iot-utilities.arubademo.de/docs/images/documentation_logo.svg"

aux_links:
  "IoT-Utilities on GitHub":
    - "https://github.com/FluegelsApps/iot-utilities/"

search:
  heading_level: 4